BASE_CFG : './configs/BaseConfig/faster_rcnn.yaml'
DATA_CFG : './configs/DataConfig/COCO-Detection.yaml'
OUTPUT_DIR : './output_coco/faster_R50_PANet'

MODEL:
  BACKBONE : 'PANet'
  WEIGHTS : './pretrained_weights/R-50.pkl'
  ROI:
    IN_FEATURES : ["n2", "n3", "n4", "n5"]
  RPN :
    IN_FEATURES : ["n2", "n3", "n4", "n5", "n6"]