BASE_CFG : './configs/BaseConfig/faster_rcnn.yaml'
DATA_CFG : './configs/DataConfig/COCO-Detection.yaml'

WEIGHTS : './pretrained_weights/R-50.pkl'
OUTPUT_DIR : './output_coco/faster_R50_FPN'

BACKBONE : 
  NAME : 'FPN'
  RESNETS :
    ENABLE : True
  FPN : 
    ENABLE : True

META_ARCH :
  RPN :
    ENABLE : True
  ROI :
    ENABLE : True