BASE_CFG : './configs/BaseConfig/faster_rcnn.yaml'
DATA_CFG : './configs/DataConfig/COCO-Detection.yaml'
OUTPUT_DIR : './output_coco/faster_R50_FPN'

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'