BASE_CFG : './configs/BaseConfig/retinanet.yaml'
DATA_CFG : './configs/DataConfig/COCO-Detection.yaml'
OUTPUT_DIR : './output_coco/retinanet_R50_FPN'

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'