BASE_CFG : './configs/FasterRCNN/VOC-Detection/R50e2e_FPN_1x_8gpu.yaml'
OUTPUT_DIR : './output_voc/faster_R50e2e_FPN_1x_2gpu_4acc'
VIS_PERIOD : 10
# SEED : 0

SOLVER :
  ACCUMULATE : 4
  IMG_PER_BATCH : 4