BASE_CFG : './configs/FasterRCNN/VOC-Detection/Base-VOC.yaml'
OUTPUT_DIR : './output_voc/faster_R50e2e_FPN_1x_8gpu'
VIS_PERIOD : 10
# SEED : 0

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'
  RESNETS :
    DEPTH : 50