from yacs.config import CfgNode as CN

_EFFICIENTNET = CN()
_EFFICIENTNET.ENABLE = False

_EFFICIENTNET.FREEZE_AT = 0
_EFFICIENTNET.OUT_FEATURES = ['stage3', 'stage4', 'stage5', 'stage7', 'stage9']
_EFFICIENTNET.NORM = 'BN'

_EFFICIENTNET.DEPTH = CN()
_EFFICIENTNET.DEPTH.DEPTH_FACTOR = 1.0
_EFFICIENTNET.DEPTH.WIDTH_FACTOR = 1.0
_EFFICIENTNET.DEPTH.DROP_CONNECT_PROB = 0.2
_EFFICIENTNET.DEPTH.SE_RATIO = 0.25

_EFFICIENTNET.STAGE_PARAM = CN()
_EFFICIENTNET.STAGE_PARAM.NUM_LAYERS_PER_STAGE = [1, 2, 2, 3, 3, 4, 1] # B0
_EFFICIENTNET.STAGE_PARAM.OUT_CHANNELS_PER_STAGE = [16, 24, 40, 80, 112, 192, 320] # B0
_EFFICIENTNET.STAGE_PARAM.KERNEL_SIZE_PER_STAGE = [3, 3, 5, 3, 5, 5, 3]
_EFFICIENTNET.STAGE_PARAM.EXPAND_DIMS_PER_STAGE = [1, 6, 6, 6, 6, 6, 6]
_EFFICIENTNET.STAGE_PARAM.STRIDES_PER_STAGE = [1, 1, 2, 2, 2, 1, 2]
