BASE_CFG : './configs/RetinaNet/Base-RetinaNet.yaml'

LOADER :
  TRAIN_DATASET : ('voc_2007_trainval', 'voc_2012_trainval')
  TEST_DATASET : 'voc_2007_test'
  TRAIN_SHUFFLE : True
  NUM_WORKERS : 4
  ASPECT_GROUPING : True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
SOLVER :
  MAX_ITER : 18000 # 17.4 epoch
  WARMUP_ITERS : 100
  STEPS : (12000, 16000)

  CHECKPOINT_PERIOD : 3000
  CHECKPOINT_KEEP : 0

TEST :
  DETECTIONS_PER_IMAGE : 100
  EVAL_PERIOD : 3000

MODEL :
  RETINANET :
    NUM_CLASSES : 20
