BASE_CFG : './configs/RetinaNet/VOC-Detection/R50_FPN_1x_8gpu.yaml'
OUTPUT_DIR : './output_voc/retinanet_R50_FPN_3x_4gpu'
SEED : 0

SOLVER :
  ACCUMULATE : 1
  MAX_ITER : 36000
  IMG_PER_BATCH : 8
  BASE_LR : 0.005
  WARMUP_ITERS : 2000
  STEPS : (24000, 32000)
  CHECKPOINT_PERIOD : 5000

TEST :
  EVAL_PERIOD : 5000