BASE_CFG : './configs/RetinaNet/VOC-Detection/R50_FPN_1x_8gpu.yaml'
OUTPUT_DIR : './output_voc/retinanet_R50_FPN_3x_2gpu_2acc'
SEED : 0

SOLVER :
  ACCUMULATE : 2
  MAX_ITER : 72000
  IMG_PER_BATCH : 4
  BASE_LR : 0.005
  WARMUP_ITERS : 400
  STEPS : (48000, 64000)
  CHECKPOINT_PERIOD : 10000

TEST :
  EVAL_PERIOD : 10000