BASE_CFG : './configs/VOC-Detection/faster_R50_PANet.yaml'
OUTPUT_DIR : './output_voc/plan/faster_R50_PANet'

BACKBONE :
  PLAN :
    ENABLE : True
    INTERLAYER_MODE : 'Default'
    FUSE_MODE : 'SENet'
    REPEAT : 4
    PLAN_CFG : 'h4k64v64e3'
