BASE_CFG : './configs/VOC-Detection/faster_R50_NASFPN.yaml'
OUTPUT_DIR : './output_voc/plan/faster_R50_NASFPN'

BACKBONE :
  NAME : 'PLAN'
  PLAN :
    ENABLE : True
    PYRAMID_NAME : 'NAS_FPN'
    INTERLAYER_MODE : 'Default'
    FUSE_MODE : 'SENet'
    REPEAT : 1
    PLAN_CFG : 'h8k64v64e5'
