BASE_CFG : './configs/VOC-Detection/retinanet_R50_FPN.yaml'
OUTPUT_DIR : './output_voc/plan/retinanet_R50_FPN'

BACKBONE :
  PLAN :
    ENABLE : True
    INTERLAYER_MODE : 'Default'
    FUSE_MODE : 'Summation'
    PLAN_CFG : 'h4k64v64e5r2'
