BASE_CFG : './configs/FasterRCNN/COCO-Detection/Base-COCO.yaml'
OUTPUT_DIR : './output_coco/faster_R50e2e_FPN_1x_8gpu'
VIS_PERIOD : 10
# SEED : 0

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'
  RESNETS :
    DEPTH : 50