from yacs.config import CfgNode as CN

_RESNET = CN()

_RESNET.DEPTH = 50
_RESNET.NUM_CLASSES = 0
_RESNET.OUT_FEATURES = ["res4"]
_RESNET.NORM = 'BN'
_RESNET.STEM_OUT_CHANNELS = 64
_RESNET.RES2_OUT_CHANNELS = 256
_RESNET.RES5_DILATION = 1
_RESNET.NUM_GROUPS = 1
_RESNET.WIDTH_PER_GROUP = 64
_RESNET.STRIDE_IN_1X1 = True