from yacs.config import CfgNode as CN

_RETINANET = CN()

_RETINANET.NUM_CLASSES = 80
_RETINANET.IN_FEATURES = ['p3', 'p4', 'p5', 'p6', 'p7']
_RETINANET.NUM_CONVS = 4
_RETINANET.IOU_THRESHOLDS = [0.4, 0.5]
_RETINANET.IOU_LABELS = [0, -1, 1]
_RETINANET.PRIOR_PROB = 0.01
_RETINANET.SCORE_THRESH_TEST = 0.05
_RETINANET.TOPK_CANDIDATES_TEST = 1000
_RETINANET.NMS_THRESH_TEST = 0.5
_RETINANET.BBOX_REG_WEIGHTS = [1.0, 1.0, 1.0, 1.0]
_RETINANET.FOCAL_LOSS_GAMMA = 2.0
_RETINANET.FOCAL_LOSS_ALPHA = 0.25
_RETINANET.SMOOTH_L1_LOSS_BETA = 0.1