from yacs.config import CfgNode as CN

_RETINANET = CN()

_RETINANET.IN_FEATURES = ['p3', 'p4', 'p5', 'p6', 'p7']
_RETINANET.NUM_CLASSES = 80

_RETINANET.MATCHER = CN()
_RETINANET.MATCHER.IOU_THRESHOLDS = [0.4, 0.5]
_RETINANET.MATCHER.IOU_LABELS = [0, -1, 1]
_RETINANET.MATCHER.LOW_QUALITY_MATCHES = True

_RETINANET.LOSS = CN()
_RETINANET.LOSS.FOCAL_GAMMA = 2.0
_RETINANET.LOSS.FOCAL_ALPHA = 0.25
_RETINANET.LOSS.SMOOTH_L1_BETA = 0.1
_RETINANET.LOSS.NORMALIZER = 100.0
_RETINANET.LOSS.NORMALIZER_MOMENTUM = 0.9

_RETINANET.HEAD = CN()
_RETINANET.HEAD.NUM_CONVS = 4
_RETINANET.HEAD.PRIOR_PROB = 0.01

_RETINANET.TEST = CN()
_RETINANET.TEST.BBOX_REG_WEIGHTS = [1.0, 1.0, 1.0, 1.0]
_RETINANET.TEST.TOPK_CANDIDATES = 1000
_RETINANET.TEST.NMS_THRESH = 0.5