from yacs.config import CfgNode as CN

_ROI_HEAD = CN()

_ROI_HEAD.IN_FEATURES = ["p2", "p3", "p4", "p5", "p6"]
_ROI_HEAD.IOU_THRESHOLDS = [0.5]
_ROI_HEAD.IOU_LABELS = [0, 1]
_ROI_HEAD.PROPOSAL_APPEND_GT = True
_ROI_HEAD.NUM_CLASSES = 80
_ROI_HEAD.BATCH_SIZE_PER_IMAGE = 512
_ROI_HEAD.POSITIVE_FRACTION = 0.5