from yacs.config import CfgNode as CN

_RPN = CN()

_RPN.HEAD_NAME = "StandardRPNHead"

_RPN.IN_FEATURES = ["res4"]
_RPN.BATCH_SIZE_PER_IMAGE = 256
_RPN.POSITIVE_FRACTION = 0.5

_RPN.BBOX_REG_LOSS_TYPE = "smooth_l1"
_RPN.SMOOTH_L1_BETA = 0.0
_RPN.LOSS_WEIGHT = 1.0
_RPN.BBOX_REG_LOSS_WEIGHT = 1.0

_RPN.BBOX_REG_WEIGHTS = (1.0, 1.0, 1.0, 1.0)
_RPN.IOU_THRESHOLDS = [0.3, 0.7]
_RPN.IOU_LABELS = [0, -1, 1]
# _RPN.BOUNDARY_THRESH = -1

# _RPN.PRE_NMS_TOPK_TRAIN = 12000
# _RPN.PRE_NMS_TOPK_TEST = 6000
# _RPN.POST_NMS_TOPK_TRAIN = 2000
# _RPN.POST_NMS_TOPK_TEST = 1000
# _RPN.NMS_THRESH = 0.7