INPUT: 
  FORMAT : 'BGR'
  RESIZE : 
    MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
    MIN_SIZE_TEST: 800

LOADER :
  TRAIN_DATASET : ('voc_2007_trainval', 'voc_2012_trainval')
  TEST_DATASET : 'voc_2007_test'
  TRAIN_SHUFFLE : True
  NUM_WORKERS : 4
  ASPECT_GROUPING : True
  

SOLVER :
  MAX_ITER : 18000 # 17.4 epoch
  SCHEDULER :
    STEPS : (12000, 16000)
  WARMUP :
    ITERS : 100
  CHECKPOINT_PERIOD : 1000
  CHECKPOINT_KEEP : 0

TEST :
  SCORE_THRESH : 0.05
  DETECTIONS_PER_IMAGE : 100
  EVAL_PERIOD : 1000
  WRITER_PERIOD : 20
  VIS_PERIOD : 20

META_ARCH :
  NUM_CLASSES : 20
