BASE_CFG : './configs/BaseConfig/faster_rcnn.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'
OUTPUT_DIR : './output_voc/faster_R50_NASFPN'

MODEL:
  BACKBONE : 'NAS_FPN'
  WEIGHTS : './pretrained_weights/R-50.pkl'