BASE_CFG : './configs/BaseConfig/faster_rcnn.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'
OUTPUT_DIR : './output_voc/faster_R50_NASFPN'

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'
  BACKBONE : 'NAS_FPN'
  
  RESNETS :
    ENABLE : True
  FPN : 
    ENABLE : True
  NAS_FPN :
    ENABLE : True
  RPN :
    ENABLE : True
  ROI :
    ENABLE : True