BASE_CFG : './configs/BaseConfig/retinanet.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'
OUTPUT_DIR : './output_voc/retinanet_R50_PANet'

MODEL:
  BACKBONE : 'PANet'
  WEIGHTS : './pretrained_weights/R-50.pkl'
  RETINANET :
    IN_FEATURES : ['n3', 'n4', 'n5', 'n6', 'n7']