BASE_CFG : './configs/BaseConfig/retinanet.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'

WEIGHTS : './pretrained_weights/R-50.pkl'
OUTPUT_DIR : './output_voc/retinanet_R50_FPN'

BACKBONE : 
  NAME : 'FPN'
  RESNETS :
    ENABLE : True
  FPN : 
    ENABLE : True

META_ARCH : 
  RETINANET :
    ENABLE : True