BASE_CFG : './configs/BaseConfig/rpn.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'

WEIGHTS : './pretrained_weights/R-50.pkl'
OUTPUT_DIR : './output_voc/rpn_R50_FPN'

BACKBONE : 
  NAME : 'FPN'
  RESNETS :
    ENABLE : True
  FPN : 
    ENABLE : True

META_ARCH :
  RPN :
    ENABLE : True