BASE_CFG : './configs/BaseConfig/rpn.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'
OUTPUT_DIR : './output_voc/rpn_R50_PANet'

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'
  BACKBONE : 'PANet'

  RESNETS :
    ENABLE : True
  FPN : 
    ENABLE : True
  PANET :
    ENABLE : True
  RPN :
    ENABLE : True
    IN_FEATURES : ["n2", "n3", "n4", "n5", "n6"]