BASE_CFG : './configs/BaseConfig/rpn.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'
OUTPUT_DIR : './output_voc/rpn_R50_PANet'

MODEL:
  BACKBONE : 'PANet'
  WEIGHTS : './pretrained_weights/R-50.pkl'
  RPN :
    IN_FEATURES : ["n2", "n3", "n4", "n5", "n6"]