BASE_CFG : './configs/BaseConfig/rpn.yaml'
DATA_CFG : './configs/DataConfig/VOC-Detection.yaml'
OUTPUT_DIR : './output_voc/rpn_R50_FPN'

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'
  BACKBONE : 'FPN'
  
  RESNETS :
    ENABLE : True
  FPN : 
    ENABLE : True
  RPN :
    ENABLE : True