BASE_CFG : './configs/base.yaml'

LOADER :
  TRAIN_DATASET : 'coco_2017_train'
  TEST_DATASET : 'coco_2017_val'
  TRAIN_SHUFFLE : True
  NUM_WORKERS : 4

MODEL :
  WEIGHTS : './pretrained_weights/R-50.pkl'
  ANCHOR_GENERATOR:
    NAME : 'DefaultAnchorGenerator'
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"] 
    ASPECT_RATIOS : [[0.5, 1.0, 2.0]]
  RESNETS : 
    OUT_FEATURES : ['res3', 'res4', 'res5']
    NORM : 'FrozenBN'

SOLVER :
  OPTIMIZER : 'SGD'
  MAX_ITER : 90000
  IMG_PER_BATCH : 2
  BASE_LR : 0.00125
  STEPS : (60000, 80000)

  CHECKPOINT_PERIOD : 1000
  CHECKPOINT_KEEP : 5

TEST :
  EVAL_PERIOD : 1000