BASE_CFG : './configs/base.yaml'
OUTPUT_DIR : './outputs/4gpu'
SEED : 0

LOADER :
  # TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TRAIN_DATASET : 'voc_2007_trainval'
  TEST_DATASET : 'voc_2007_test'

SOLVER :
  MAX_ITER : 180000
  IMG_PER_BATCH : 2
  BASE_LR : 0.005
  STEPS : (80000, 160000)
  ACCUMULATE : 1

TEST :
  EVAL_PERIOD : 10000