BASE_CFG : './configs/Base-RetinaNet.yaml'

LOADER :
  TRAIN_DATASET : ('coco_2017_train', )
  TEST_DATASET : 'coco_2017_val'
  TRAIN_SHUFFLE : True
  NUM_WORKERS : 4
  ASPECT_GROUPING : True

SOLVER :
  OPTIMIZER : 'SGD'
  ACCUMULATE : 1
  IMG_PER_BATCH : 16
  BASE_LR : 0.01
  MAX_ITER : 90000
  WARMUP_ITERS : 1000
  STEPS : (60000, 80000)

  CHECKPOINT_PERIOD : 5000
  CHECKPOINT_KEEP : 0

TEST :
  DETECTIONS_PER_IMAGE : 100
  EVAL_PERIOD : 5000

MODEL :
  RESNETS : 
    NUM_CLASSES : 80
  RETINANET :
    NUM_CLASSES : 80