BASE_CFG : './configs/Base-RetinaNet.yaml'

LOADER :
  TRAIN_DATASET : ('voc_2007_trainval', 'voc_2012_trainval')
  TEST_DATASET : 'voc_2007_test'
  TRAIN_SHUFFLE : True
  NUM_WORKERS : 4
  ASPECT_GROUPING : True

SOLVER :
  OPTIMIZER : 'SGD'
  ACCUMULATE : 1
  IMG_PER_BATCH : 16
  BASE_LR : 0.01
  MAX_ITER : 18000 # 17.4 epoch
  WARMUP_ITERS : 100
  STEPS : (12000, 16000)

  CHECKPOINT_PERIOD : 5000
  CHECKPOINT_KEEP : 0

TEST :
  DETECTIONS_PER_IMAGE : 100
  EVAL_PERIOD : 5000

MODEL :
  RETINANET :
    NUM_CLASSES : 20
