MODEL :
  META_ARCHITECTURE : 'FasterRCNN'
  BACKBONE : 'FPN'
  PROPOSAL_GENERATOR : 'RPN'
  WEIGHTS : './pretrained_weights/R-50.pkl'

  ANCHOR_GENERATOR:
    NAME : 'DefaultAnchorGenerator'
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS : [[0.5, 1.0, 2.0]]
  RESNETS : 
    DEPTH : 50
    OUT_FEATURES : ['res2', 'res3', 'res4', 'res5']
    NORM : 'FrozenBN'
  FPN :
    NAME : 'ResNetFPN'
    IN_FEATURES : ['res2', 'res3', 'res4', 'res5']
  NAS_FPN:
    CELL_INPUTS : [['p5', 'p3'],['rcb1', 'p3'],['rcb2', 'p2'],['rcb3', 'rcb2'],['rcb3', 'rcb4', 'p4'],['rcb2', 'rcb5', 'p6'],['rcb5', 'rcb6']]
    CELL_OUTPUTS : ['p3', 'p3', 'p2', 'p3', 'p4', 'p6', 'p5']
    CELL_OPS : ['GP', 'SUM', 'SUM', 'SUM', 'GP_SUM', 'GP_SUM', 'GP']
    NAS_OUTPUTS : ['rcb3','rcb4','rcb5','rcb7','rcb6']
  ROI:
    NAME : 'StandardROIHeads'
    IN_FEATURES : ["p2", "p3", "p4", "p5"]
    MATCHER:
      IOU_THRESHOLDS : [0.5]
      IOU_LABELS : [0, 1]
      LOW_QUALITY_MATCHES : False
    BOX_POOLING:
      TYPE : 'ROIAlignV2'
      RESOLUTION : 7
    BOX_HEAD : 
      NUM_FC : 2
  RPN :
    HEAD_NAME : 'StandardRPNHead'
    IN_FEATURES : ["p2", "p3", "p4", "p5", "p6"]
    MATCHER :
      IOU_THRESHOLDS : [0.3, 0.7]
      IOU_LABELS : [0, -1, 1]
      LOW_QUALITY_MATCHES : True
    TRAIN :
      PRE_NMS_TOPK: 2000  # Per FPN level
      POST_NMS_TOPK: 1000
    TEST : 
      PRE_NMS_TOPK: 1000  # Per FPN level
      POST_NMS_TOPK: 1000

SOLVER :
  OPTIMIZER : 'SGD'
  IMG_PER_BATCH : 16
  BASE_LR : 0.02