BACKBONE :
  NAME : 'FPN'
  RESNETS : 
    DEPTH : 50
    OUT_FEATURES : ['res3', 'res4', 'res5']
    NORM : 'FrozenBN'
    STEM_BIAS : False
  FPN :
    NAME : 'RetinaNetFPN'
    IN_FEATURES : ['res3', 'res4', 'res5']
  NAS_FPN:
    CELL_INPUTS : [['p6', 'p4'],['rcb1', 'p4'],['rcb2', 'p3'],['rcb3', 'rcb2'],['rcb3', 'rcb4', 'p5'],['rcb2', 'rcb5', 'p7'],['rcb5', 'rcb6']]
    CELL_OUTPUTS : ['p4', 'p4', 'p3', 'p4', 'p5', 'p7', 'p6']
    CELL_OPS : ['GP', 'SUM', 'SUM', 'SUM', 'GP_SUM', 'GP_SUM', 'GP']
    NAS_OUTPUTS : ['rcb3','rcb4','rcb5','rcb7','rcb6']
  PANET:
    IN_FEATURES : ['p3', 'p4', 'p5', 'p6', 'p7']
    OUT_CHANNELS : 256

META_ARCH : 
  NAME : 'RetinaNet'
  RETINANET :
    IN_FEATURES : ['p3', 'p4', 'p5', 'p6', 'p7']
    MATCHER:
      IOU_THRESHOLDS : [0.4, 0.5]
      IOU_LABELS : [0, -1, 1]
      LOW_QUALITY_MATCHES : True
    LOSS :
      NORMALIZER : 100.0
      NORMALIZER_MOMENTUM : 0.9
    HEAD :
      NUM_CONVS : 4

ANCHOR_GENERATOR:
  NAME : 'DefaultAnchorGenerator'
  SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"] 
  ASPECT_RATIOS : [[0.5, 1.0, 2.0]]

SOLVER :
  OPTIMIZER : 'SGD'
  IMG_PER_BATCH : 16
  BASE_LR : 0.01