BASE_CFG : './configs/BaseConfig/efficientnet.yaml'
DATA_CFG : './configs/DataConfig/ImageNet-Classification.yaml'

WEIGHTS : './pretrained_weights/efficientnet-b4-6ed6700e.pth'
OUTPUT_DIR : './output_imagenet/efficientnet_B4'


BACKBONE :
  EFFICIENTNET : 
    DEPTH :
      DEPTH_FACTOR : 1.8
      WIDTH_FACTOR : 1.4

META_ARCH : 
  EFFICIENTNET :
    DROPOUT_PROB : 0.4