BASE_CFG : './configs/BaseConfig/efficientnet.yaml'
DATA_CFG : './configs/DataConfig/ImageNet-Classification.yaml'

WEIGHTS : './pretrained_weights/efficient-b2-8bb594d6'
OUTPUT_DIR : './output_imagenet/efficientnet_B2'


BACKBONE :
  EFFICIENTNET : 
    DEPTH :
      DEPTH_FACTOR : 1.2
      WIDTH_FACTOR : 1.1

META_ARCH : 
  EFFICIENTNET :
    DROPOUT_PROB : 0.3