BASE_CFG : './configs/BaseConfig/efficientnet.yaml'
DATA_CFG : './configs/DataConfig/ImageNet-Classification.yaml'

WEIGHTS : './pretrained_weights/efficient-b3-5fb5a3c3'
OUTPUT_DIR : './output_imagenet/efficientnet_B3'


BACKBONE :
  EFFICIENTNET : 
    DEPTH :
      DEPTH_FACTOR : 1.4
      WIDTH_FACTOR : 1.2

META_ARCH : 
  EFFICIENTNET :
    DROPOUT_PROB : 0.3