BASE_CFG : './configs/BaseConfig/efficientnet.yaml'
DATA_CFG : './configs/DataConfig/ImageNet-Classification.yaml'

WEIGHTS : './pretrained_weights/efficientnet-b6-c76e70fd.pth'
OUTPUT_DIR : './output_imagenet/efficientnet_B6'


BACKBONE :
  EFFICIENTNET : 
    DEPTH :
      DEPTH_FACTOR : 2.6
      WIDTH_FACTOR : 1.8

META_ARCH : 
  EFFICIENTNET :
    DROPOUT_PROB : 0.5