BASE_CFG : './configs/BaseConfig/efficientnet.yaml'
DATA_CFG : './configs/DataConfig/ImageNet-Classification.yaml'

WEIGHTS : './pretrained_weights/efficient-b7-dcc49843'
OUTPUT_DIR : './output_imagenet/efficientnet_B7'


BACKBONE :
  EFFICIENTNET : 
    DEPTH :
      DEPTH_FACTOR : 3.1
      WIDTH_FACTOR : 2.0

META_ARCH : 
  EFFICIENTNET :
    DROPOUT_PROB : 0.5