BASE_CFG : './configs/RetinaNet/Base-RetinaNet.yaml'

LOADER :
  TRAIN_DATASET : ('coco_2017_train', )
  TEST_DATASET : 'coco_2017_val'
  TRAIN_SHUFFLE : True
  NUM_WORKERS : 4
  ASPECT_GROUPING : True

SOLVER :
  MAX_ITER : 90000
  WARMUP_ITERS : 1000
  STEPS : (60000, 80000)

  CHECKPOINT_PERIOD : 5000
  CHECKPOINT_KEEP : 0

TEST :
  DETECTIONS_PER_IMAGE : 100
  EVAL_PERIOD : 5000

MODEL :
  RETINANET :
    NUM_CLASSES : 80