BASE_CFG : './configs/RetinaNet/Base.yaml'

INPUT: 
  FORMAT : 'BGR'
  RESIZE : 
    MIN_SIZE_TRAIN: (600, 672, 704, 736, 768, 800)
    MIN_SIZE_TEST: 800

LOADER :
  TRAIN_DATASET : ('coco_2017_train', )
  TEST_DATASET : 'coco_2017_val'
  TRAIN_SHUFFLE : True
  NUM_WORKERS : 4
  ASPECT_GROUPING : True

SOLVER :
  MAX_ITER : 90000
  SCHEDULER :
    STEPS : (60000, 80000)
  WARMUP :
    ITERS : 1000
  CHECKPOINT_PERIOD : 5000
  CHECKPOINT_KEEP : 0

TEST :
  SCORE_THRESH : 0.05
  DETECTIONS_PER_IMAGE : 100
  EVAL_PERIOD : 5000
  WRITER_PERIOD : 20
  VIS_PERIOD : 20

MODEL :
  RETINANET :
    NUM_CLASSES : 80