BASE_CFG : './configs/RetinaNet/COCO-Detection/Base-COCO.yaml'
OUTPUT_DIR : './output_coco/retinanet_R50_FPN_1x_8gpu'
VIS_PERIOD : 10
SEED : 0

MODEL:
  WEIGHTS : './pretrained_weights/R-50.pkl'
  RESNETS :
    DEPTH : 50