BASE_CFG : './configs/RetinaNet/COCO-Detection/R50_FPN-1x_8gpu.yaml'
OUTPUT_DIR : './outputs/retinanet_R50_FPN_3x_8gpu'

SOLVER :
  MAX_ITER : 270000
  STEPS : (210000, 250000)
  CHECKPOINT_PERIOD : 10000

TEST :
  EVAL_PERIOD : 10000
