from yacs.config import CfgNode as CN

_INPUT = CN()

_INPUT.FORMAT = 'BGR'
_INPUT.PIXEL_MEAN = [103.530, 116.280, 123.675]
_INPUT.PIXEL_STD = [1.0, 1.0, 1.0]

_INPUT.EXIF = True
_INPUT.TRANSFORM = ['ResizeShortestEdge', 'RandomFlip']

_INPUT.RESIZE = CN()
_INPUT.RESIZE.ENABLE = True
_INPUT.RESIZE.MIN_SIZE_TRAIN_SAMPLING = 'choice'
_INPUT.RESIZE.MIN_SIZE_TRAIN = (600, 672, 704, 736, 768, 800)
_INPUT.RESIZE.MAX_SIZE_TRAIN = 1333
_INPUT.RESIZE.MIN_SIZE_TEST = 800
_INPUT.RESIZE.MAX_SIZE_TEST = 1333

_INPUT.FLIP = CN()
_INPUT.FLIP.ENABLE = True
_INPUT.FLIP.PROB = 0.5

_INPUT.CROP = CN()
_INPUT.CROP.ENABLE = False
_INPUT.CROP.TYPE = 'relative_range'
_INPUT.CROP.SIZE = [0.9, 0.9]