from yacs.config import CfgNode as CN

_SOLVER = CN()

_SOLVER.OPTIMIZER = 'SGD'
_SOLVER.MAX_ITER = 90000
_SOLVER.IMG_PER_BATCH = 16
_SOLVER.BASE_LR = 0.01

_SOLVER.WEIGHT_DECAY = 0.0001
_SOLVER.WEIGHT_DECAY_NORM = 0.0
_SOLVER.WEIGHT_DECAY_BIAS = 0.0001
_SOLVER.BIAS_LR_FACTOR = 1.0
_SOLVER.MOMENTUM = 0.9

_SOLVER.LR_SCHEDULER_NAME = 'WarmupMultiStepLR'
_SOLVER.WARMUP_FACTOR = 0.001
_SOLVER.WARMUP_ITERS = 1000
_SOLVER.WARMUP_METHOD = 'linear'
_SOLVER.STEPS = (60000, 80000)
_SOLVER.GAMMA = 0.1

_SOLVER.CHECKPOINT_PERIOD = 1000
_SOLVER.CHECKPOINT_KEEP = 0