from yacs.config import CfgNode as CN

_EFFICIENTDET = CN()
_EFFICIENTDET.ENABLE = False

_EFFICIENTDET.IN_FEATURES = ['p3', 'p4', 'p5', 'p6', 'p7']

_EFFICIENTDET.MATCHER = CN()
_EFFICIENTDET.MATCHER.IOU_THRESHOLDS = [0.4, 0.5]
_EFFICIENTDET.MATCHER.IOU_LABELS = [0, -1, 1]
_EFFICIENTDET.MATCHER.LOW_QUALITY_MATCHES = True

_EFFICIENTDET.LOSS = CN()
_EFFICIENTDET.LOSS.FOCAL_GAMMA = 1.5
_EFFICIENTDET.LOSS.FOCAL_ALPHA = 0.25
_EFFICIENTDET.LOSS.SMOOTH_L1_BETA = 0.1
_EFFICIENTDET.LOSS.NORMALIZER = 100.0
_EFFICIENTDET.LOSS.NORMALIZER_MOMENTUM = 0.9

_EFFICIENTDET.HEAD = CN()
_EFFICIENTDET.HEAD.NUM_CONVS = 3
_EFFICIENTDET.HEAD.PRIOR_PROB = 0.01

_EFFICIENTDET.TEST = CN()
_EFFICIENTDET.TEST.BBOX_REG_WEIGHTS = [1.0, 1.0, 1.0, 1.0]
_EFFICIENTDET.TEST.TOPK_CANDIDATES = 1000
_EFFICIENTDET.TEST.NMS_THRESH = 0.5