from yacs.config import CfgNode as CN

_ROI = CN()
_ROI.ENABLE = False

_ROI.NAME = 'StandardROIHeads'
_ROI.IN_FEATURES = ["p2", "p3", "p4", "p5", "p6"]
_ROI.NUM_CLASSES = 80

_ROI.MATCHER = CN()
_ROI.MATCHER.IOU_THRESHOLDS = [0.5]
_ROI.MATCHER.IOU_LABELS = [0, 1]
_ROI.MATCHER.LOW_QUALITY_MATCHES = False

_ROI.SAMPLING = CN()
_ROI.SAMPLING.PROPOSAL_APPEND_GT = True
_ROI.SAMPLING.BATCH_SIZE_PER_IMAGE = 512
_ROI.SAMPLING.POSITIVE_FRACTION = 0.5

_ROI.BOX_POOLING = CN()
_ROI.BOX_POOLING.TYPE = "ROIAlignV2"
_ROI.BOX_POOLING.RESOLUTION = 14
_ROI.BOX_POOLING.SAMPLING_RATIO = 0

_ROI.BOX_HEAD = CN()
_ROI.BOX_HEAD.NUM_CONV = 0
_ROI.BOX_HEAD.CONV_DIM = 256
_ROI.BOX_HEAD.CONV_NORM = ''
_ROI.BOX_HEAD.NUM_FC = 0
_ROI.BOX_HEAD.FC_DIM = 1024

_ROI.BOX_LOSS = CN()
_ROI.BOX_LOSS.LOSS_WEIGHT = 1.0
_ROI.BOX_LOSS.SMOOTH_L1_BETA = 0.0

_ROI.TEST = CN()
_ROI.TEST.BBOX_REG_WEIGHTS = (10.0, 10.0, 5.0, 5.0)
_ROI.TEST.NMS_THRESH = 0.5
